version: '3'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"
    networks:
      - example-app_default

  redis:
    image: redis
    networks:
      - example-app_default

  laravel.test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - example-app_default

networks:
  example-app_default:
    driver: bridge
